services:
    php:
        build:
            context: ./docker/app/
            dockerfile: Dockerfile
        container_name: cinema-online-php
        restart: unless-stopped
        working_dir: '/var/www'
        volumes:
            - './:/var/www/'
        depends_on:
            - mysql
        networks:
            - cinema-online-network

    mysql:
        image: mysql:8
        ports:
            - '3306:3306'
        container_name: cinema-online-mysql
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_USER=$DB_USERNAME
            - MYSQL_PASSWORD=$DB_PASSWORD
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        volumes:
            - './docker/volume/mysql:/var/lib/mysql'
        networks:
            - cinema-online-network

    nginx:
        image: nginx:latest
        container_name: cinema-online-nginx
        restart: unless-stopped
        ports:
            - '9000:80'
        volumes:
            - './:/var/www'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - cinema-online-network

networks:
    cinema-online-network:
        driver: bridge
volumes:
    cinema-online-mysql:
        driver: local
